In [1]:
a = {"Laura": 92.4, "Sofia": 87.5}

In [2]:
print (a)

{'Laura': 92.4, 'Sofia': 87.5}

In [3]:
b = dict(Name="Laura", Age=4)

In [4]:
print (b)

{'Name': 'Laura', 'Age': 4}

In [5]:
print(b["Name"])

Laura

In [6]:
print(b["Age"])

4

In [7]:
c = {"Name": "Sofia"}

In [8]:
print (c)

{'Name': 'Sofia'}

In [9]:
print(c["Name"])

Sofia

In [10]:
#RNA seq results

In [11]:
gene = {"BRCA1": 8716, "TP53": 1262, "MYC": 26523}

In [12]:
print(gene["MYC"])

26523

In [13]:
print(gene["TP53"])

1262

In [25]:
print(gene["BRCA1"])

8716

In [26]:
gene["RB1"] = 7653

In [27]:
gene["PTEN"] = 9273

In [28]:
gene["PSEN1"] = 4532

In [29]:
gene["PINK1"] = 3231

In [30]:
gene["APC"] = 8676

In [31]:
print(gene)

{'BRCA1': 8716, 'TP53': 1262, 'MYC': 26523, 'RB1': 7653, 'PTEN': 9273, 'PSEN1': 4532, 'PINK1': 3231, 'APC': 8676}

In [113]:
import pandas as pd
from biopandas.pdb import PandasPdb

In [114]:
import os

In [115]:
path = "C:/Users/whynew.in"
os.chdir(path)

In [116]:
file = "2v8t"

In [117]:
ps = PandasPdb().fetch_pdb('2v8t')

In [118]:
ps

In [119]:
df = ps.df ["ATOM"]

In [120]:
df

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,MET,,A,1,,...,-14.554,28.306,10.187,1.0,8.22,,,N,NaN,850
1,ATOM,2,,CA,,MET,,A,1,,...,-13.741,29.479,9.722,1.0,7.77,,,C,NaN,852
2,ATOM,3,,C,,MET,,A,1,,...,-13.287,30.223,10.968,1.0,7.72,,,C,NaN,854
3,ATOM,4,,O,,MET,,A,1,,...,-13.838,30.010,12.041,1.0,8.12,,,O,NaN,856
4,ATOM,5,,CB,,MET,,A,1,,...,-14.536,30.420,8.799,1.0,8.94,,,C,NaN,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5030,ATOM,5032,,CB,,LYS,,B,302,,...,-29.835,26.782,36.506,0.1,53.15,,,C,NaN,10903
5031,ATOM,5033,,CG,,LYS,,B,302,,...,-28.361,26.784,36.853,0.1,53.20,,,C,NaN,10905
5032,ATOM,5034,,CD,,LYS,,B,302,,...,-27.655,25.522,36.357,0.1,53.19,,,C,NaN,10907
5033,ATOM,5035,,CE,,LYS,,B,302,,...,-28.450,24.232,36.611,0.1,53.12,,,C,NaN,10909
5034,ATOM,5036,,NZ,,LYS,,B,302,,...,-27.806,23.035,36.002,0.1,53.08,,,N,NaN,10911

In [121]:
df.columns = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17", "A18", "A19", "A20", "A21"]

In [122]:
df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21
0,ATOM,1,,N,,MET,,A,1,,...,-14.554,28.306,10.187,1.0,8.22,,,N,NaN,850
1,ATOM,2,,CA,,MET,,A,1,,...,-13.741,29.479,9.722,1.0,7.77,,,C,NaN,852
2,ATOM,3,,C,,MET,,A,1,,...,-13.287,30.223,10.968,1.0,7.72,,,C,NaN,854
3,ATOM,4,,O,,MET,,A,1,,...,-13.838,30.010,12.041,1.0,8.12,,,O,NaN,856
4,ATOM,5,,CB,,MET,,A,1,,...,-14.536,30.420,8.799,1.0,8.94,,,C,NaN,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5030,ATOM,5032,,CB,,LYS,,B,302,,...,-29.835,26.782,36.506,0.1,53.15,,,C,NaN,10903
5031,ATOM,5033,,CG,,LYS,,B,302,,...,-28.361,26.784,36.853,0.1,53.20,,,C,NaN,10905
5032,ATOM,5034,,CD,,LYS,,B,302,,...,-27.655,25.522,36.357,0.1,53.19,,,C,NaN,10907
5033,ATOM,5035,,CE,,LYS,,B,302,,...,-28.450,24.232,36.611,0.1,53.12,,,C,NaN,10909
5034,ATOM,5036,,NZ,,LYS,,B,302,,...,-27.806,23.035,36.002,0.1,53.08,,,N,NaN,10911

In [123]:
a={"C":12,"N":14,"O":16,"S":32}

In [124]:
df["A19"] = df["A19"].map(a)

In [125]:
df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21
0,ATOM,1,,N,,MET,,A,1,,...,-14.554,28.306,10.187,1.0,8.22,,,14,NaN,850
1,ATOM,2,,CA,,MET,,A,1,,...,-13.741,29.479,9.722,1.0,7.77,,,12,NaN,852
2,ATOM,3,,C,,MET,,A,1,,...,-13.287,30.223,10.968,1.0,7.72,,,12,NaN,854
3,ATOM,4,,O,,MET,,A,1,,...,-13.838,30.010,12.041,1.0,8.12,,,16,NaN,856
4,ATOM,5,,CB,,MET,,A,1,,...,-14.536,30.420,8.799,1.0,8.94,,,12,NaN,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5030,ATOM,5032,,CB,,LYS,,B,302,,...,-29.835,26.782,36.506,0.1,53.15,,,12,NaN,10903
5031,ATOM,5033,,CG,,LYS,,B,302,,...,-28.361,26.784,36.853,0.1,53.20,,,12,NaN,10905
5032,ATOM,5034,,CD,,LYS,,B,302,,...,-27.655,25.522,36.357,0.1,53.19,,,12,NaN,10907
5033,ATOM,5035,,CE,,LYS,,B,302,,...,-28.450,24.232,36.611,0.1,53.12,,,12,NaN,10909
5034,ATOM,5036,,NZ,,LYS,,B,302,,...,-27.806,23.035,36.002,0.1,53.08,,,14,NaN,10911

In [126]:
dfA = df[df["A8"]=="A"]

In [127]:
dfA

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21
0,ATOM,1,,N,,MET,,A,1,,...,-14.554,28.306,10.187,1.0,8.22,,,14,NaN,850
1,ATOM,2,,CA,,MET,,A,1,,...,-13.741,29.479,9.722,1.0,7.77,,,12,NaN,852
2,ATOM,3,,C,,MET,,A,1,,...,-13.287,30.223,10.968,1.0,7.72,,,12,NaN,854
3,ATOM,4,,O,,MET,,A,1,,...,-13.838,30.010,12.041,1.0,8.12,,,16,NaN,856
4,ATOM,5,,CB,,MET,,A,1,,...,-14.536,30.420,8.799,1.0,8.94,,,12,NaN,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,ATOM,2515,,CB,,LYS,,A,302,,...,-9.149,53.817,-3.769,0.4,42.07,,,12,NaN,5875
2515,ATOM,2516,,CG,,LYS,,A,302,,...,-8.375,53.244,-4.933,0.4,42.52,,,12,NaN,5877
2516,ATOM,2517,,CD,,LYS,,A,302,,...,-8.102,54.289,-6.008,0.4,42.69,,,12,NaN,5879
2517,ATOM,2518,,CE,,LYS,,A,302,,...,-7.347,53.699,-7.173,0.4,42.93,,,12,NaN,5881
2518,ATOM,2519,,NZ,,LYS,,A,302,,...,-6.755,54.782,-7.999,0.4,43.64,,,14,NaN,5883

In [128]:
dfB=dfA[pd.to_numeric(dfA["A9"])<11]

In [129]:
dfB

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21
0,ATOM,1,,N,,MET,,A,1,,...,-14.554,28.306,10.187,1.0,8.22,,,14,NaN,850
1,ATOM,2,,CA,,MET,,A,1,,...,-13.741,29.479,9.722,1.0,7.77,,,12,NaN,852
2,ATOM,3,,C,,MET,,A,1,,...,-13.287,30.223,10.968,1.0,7.72,,,12,NaN,854
3,ATOM,4,,O,,MET,,A,1,,...,-13.838,30.010,12.041,1.0,8.12,,,16,NaN,856
4,ATOM,5,,CB,,MET,,A,1,,...,-14.536,30.420,8.799,1.0,8.94,,,12,NaN,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,ATOM,86,,O,,ILE,,A,10,,...,-0.864,40.588,26.284,1.0,10.37,,,16,NaN,1020
86,ATOM,87,,CB,,ILE,,A,10,,...,-2.050,39.422,29.098,1.0,10.50,,,12,NaN,1022
87,ATOM,88,,CG1,,ILE,,A,10,,...,-0.881,38.508,28.815,1.0,10.93,,,12,NaN,1024
88,ATOM,89,,CG2,,ILE,,A,10,,...,-3.148,38.756,29.933,1.0,12.89,,,12,NaN,1026
89,ATOM,90,,CD1,,ILE,,A,10,,...,-0.039,38.153,29.983,1.0,13.33,,,12,NaN,1028

In [130]:
dfA["A12"]=pd.to_numeric(dfA["A12"])

In [131]:
dfA["A19"]=pd.to_numeric(dfA["A19"])

In [132]:
dfA["A22"]=dfA["A12"] * dfA["A19"]

In [133]:
COMx=sum(dfA["A22"])/sum(dfA["A19"])

In [134]:
COMx

-0.017614880307951403

In [135]:
dfA["A13"]=pd.to_numeric(dfA["A13"])

In [136]:
dfA["A19"]=pd.to_numeric(dfA["A19"])

In [137]:
dfA["A23"] =dfA["A13"] * dfA["A19"]

In [140]:
COMx = sum(dfA["A23"])/sum(dfA["A19"])

In [141]:
COMx

30.656821664862264

In [148]:
dfA["A14"]=pd.to_numeric(dfA["A14"])

In [149]:
dfA["A19"]=pd.to_numeric(dfA["A19"])

In [150]:
dfA["A24"]=dfA["A14"] * dfA["A19"]

In [153]:
COMx = sum(dfA["A24"])/sum(dfA["A19"])

In [154]:
COMx

24.156143810898595